### ISSUE TITLE
Updating status flow doesn't work in Firefox

### ISSUE THREAD

**Issue by QuinnBast** [herasymj/Health-Esteem#10]
The new milestone4 status progression buttons do not progress the status flow of an idea. After clicking one of the buttons the user is taken to the "UpdateStatus" page.

Step 1: Find an idea
![image](https://user-images.githubusercontent.com/22599103/47757384-c2a4ed00-dc6b-11e8-80b9-3d7e82ffe967.png)
Step 2: Click one of the status progress buttons. The user is taken to the update idea page instead of immediately progressing the idea.
![image](https://user-images.githubusercontent.com/22599103/47757408-da7c7100-dc6b-11e8-8505-521aa769f2a2.png)

This is only an issue in Firefox. Works in Chrome and Edge.

**Comment by ShawnClake** [comment]
no longer valid as the page is now removed
