### ISSUE TITLE
Registration Divisions and Units don't populate

### ISSUE THREAD

**Issue by QuinnBast** [herasymj/Health-Esteem#22]
Steps to reproduce:

1. Register as normal.
2. Before clicking register ensure that the password does not meet the password criteria (missing a symbol, number, capitol, etc.)
3. Press register.
4. The division and unit drop downs will not be populated from the database and the page will need to be reloaded.

Potential solutions:
1. Reload the divisions/units on registration fail
2. Ensure the password meets the required format client-side before they can click register.

I prefer 2 but both could be implemented

**Comment by oscar666666** [comment]
Divsion options and Unit options are generated only when user opens a new registration page. Controller returns empty Divsion and Unit "select" classes when registration was failed.

Example:
 ```
<div class="form-group">
                        <label>Division</label>
                        <select class="form-control" id="division" data-val="true" data-val-required="The Division field is required." name="Input.DivisionID">
_**Missing options here**_
                        </select>
                    </div>
```

**Comment by oscar666666** [comment]
Potential fix:
Redirect user back to 
`http://localhost:49206/Identity/Account/Register`
instead of
`http://localhost:49206/Identity/Account/Register?createdByAdmin=False`
when registration failed.

**Comment by QuinnBast** [comment]
Completed with commit indicated above ^
Simply regenerated the page model on a failed registration.
